### ISSUE TITLE
Обновить/пополнить список операций в фильтре

### ISSUE THREAD

**Issue by jackvote** [golos-blockchain/ui-explorer#1]
Отсутствуют операции Claim, Donate и пр. ещё с прошлого hf.

[id="about-account-filter"](https://github.com/golos-blockchain/golos-explorer/blob/eb41cf89bcee024f248780119be96b337a057602/index.html#L353)

**Comment by Lex-Ai** [comment]
https://github.com/golos-blockchain/golos-explorer/commit/11f51fcc3c21b9c91c551709ff2c24af92a99641
